import six as _six

from flytekit.common.types.helpers import pack_python_std_map_to_literal_map as _packer
from flytekit.contrib.notebook.supported_types import notebook_types_map as _notebook_types_map


def record_outputs(outputs=None):
    """
    Converts/Records outputs generated by users in their Notebook as Flyte Types.
    """
    if outputs is None:
        return _packer({}, {})
    tm = {}
    for k, v in _six.iteritems(outputs):
        t = type(v)
        if t not in _notebook_types_map:
            raise ValueError(
                "Currently only primitive types {} are supported for recording from notebook".format(
                    _notebook_types_map
                )
            )
        tm[k] = _notebook_types_map[t]
    return _packer(outputs, tm).to_flyte_idl()
