ignore:
  - "flytekit/bin"
  - "test_*.py"
  - "flytekit/__init__.py"
  - "flytekit/extend/__init__.py"
  - "flytekit/testing/__init__.py"
  - "tests/**/*"
  - "setup.py"
  - "plugins/tests/**/*"
  - "plugins/**/setup.py"
