FROM python:3.9-slim-buster

MAINTAINER Flyte Team <users@flyte.org>
LABEL org.opencontainers.image.source=https://github.com/flyteorg/flytekit

# ARG VERSION
# RUN pip install -U flytekit==$VERSION flytekitplugins-bigquery==$VERSION
RUN apt-get update && apt-get install -y git gcc

# RUN pip install --upgrade pip setuptools wheel psutil
RUN pip install apache-airflow
RUN pip install git+https://github.com/flyteorg/flytekit.git@dfb244c2ca428c68a6901957bb0656aacfac5be3#subdirectory=plugins/flytekit-airflow
RUN pip install git+https://github.com/flyteorg/flytekit.git@dfb244c2ca428c68a6901957bb0656aacfac5be3
RUN pip install msgpack

CMD pyflyte serve --port 8000
