FROM python:3.9-slim-buster

MAINTAINER Flyte Team <users@flyte.org>
LABEL org.opencontainers.image.source=https://github.com/flyteorg/flytekit

# ARG VERSION
# RUN pip install -U flytekit==$VERSION flytekitplugins-bigquery==$VERSION
RUN apt-get update && apt-get install -y git

# RUN pip install --upgrade pip setuptools wheel psutil
RUN pip install apache-airflow
RUN pip install git+https://github.com/flyteorg/flytekit.git@c7da3e74d8b658871c67343271e413812f617995#subdirectory=plugins/flytekit-airflow
RUN pip install git+https://github.com/flyteorg/flytekit.git@c7da3e74d8b658871c67343271e413812f617995
RUN pip install msgpack

CMD pyflyte serve --portd 8000
