FROM python:3.9-slim-buster

MAINTAINER Flyte Team <users@flyte.org>
LABEL org.opencontainers.image.source=https://github.com/flyteorg/flytekit

# ARG VERSION
# RUN pip install -U flytekit==$VERSION flytekitplugins-bigquery==$VERSION
RUN apt-get update && apt-get install -y git gcc

# RUN pip install --upgrade pip setuptools wheel psutil
RUN pip install apache-airflow
RUN pip install msgpack
RUN pip install google-cloud-orchestration-airflow==1.9.1
RUN pip install apache-airflow-providers-google
RUN pip install jsonpickle
# RUN pip install apache-airflow-providers-apache-hive

RUN pip install git+https://github.com/flyteorg/flytekit.git@abb3f0c0536f996c16a2551506509ce50349fb76#subdirectory=plugins/flytekit-airflow
RUN pip install git+https://github.com/flyteorg/flytekit.git@abb3f0c0536f996c16a2551506509ce50349fb76

CMD pyflyte serve --port 8000
