FROM python:3.7-slim-buster

MAINTAINER Flyte Team <users@flyte.org>
LABEL org.opencontainers.image.source https://github.com/flyteorg/flytekit

ARG $version

RUN pip install awscli
RUN pip install gsutil
RUN pip install -U flytekit==$(echo version | sed 's#.*/v##')

WORKDIR /app