[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.pytest.ini_options]
norecursedirs = ["common", "workflows", "spark"]
log_cli = true
log_cli_level = 20

[tool.coverage.run]
branch = true
