[tool.pytest.ini_options]
norecursedirs = ["common", "workflows", "spark", "fsspec"]
log_cli = true
log_cli_level = 20
markers = [
    # unit tests that are really integration tests that run on a sandbox environment
    "sandbox_test: fake integration tests",
]

[tool.coverage.run]
branch = true

[tool.ruff]
line-length = 120
select = ["E", "W", "F"]
ignore = [
    # Whitespace before '{symbol}'
    "E203",
    # Too many leading # before block comment
    "E266",
    # Line too long ({width} > {limit})
    "E501",
    # Ambiguous variable name: {name}
    "E741",
    # Undefined name {name}
    "F821",
    # Do not compare types, use isinstance()
    "E721",
    # Do not assign a lambda expression, use a def
    "E731",
]

[tool.ruff.extend-per-file-ignores]
"*/__init__.py" = [
    # unused-import
    "F401",
]
