# This file is auto-generated by flyteinteractive

from tests.test_flyteinteractive_vscode import t
from flytekitplugins.flyteinteractive import get_task_inputs

if __name__ == "__main__":
    inputs = get_task_inputs(
        task_module_name="tests.test_flyteinteractive_vscode",
        task_name="t",
        context_working_dir="/tmp/flyte-fijr94xv/sandbox/local_flytekit",
    )
    # You can modify the inputs! Ex: inputs['a'] = 5
    print(t(**inputs))
