FROM ghcr.io/flyteorg/flytekit:py3.8-1.10.0
RUN curl -kfLO https://github.com/coder/code-server/releases/download/v4.18.0/code-server-4.18.0-linux-amd64.tar.gz
RUN tar -xzf code-server-4.18.0-linux-amd64.tar.gz