INPUT_FILE_NAME = "inputs.pb"
OUTPUT_FILE_NAME = "outputs.pb"
FUTURES_FILE_NAME = "futures.pb"
ERROR_FILE_NAME = "error.pb"
REQUIREMENTS_FILE_NAME = "requirements.txt"
GLOBAL_INPUT_NODE_ID = ""

CONTAINER_ARRAY_TASK = "container_array"
START_NODE_ID = "start-node"
END_NODE_ID = "end-node"
