name: Monodocs Build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docs:
    name: Monodocs Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch flytekit code
        uses: actions/checkout@v4
      - name: 'Clear action cache'
        uses: ./.github/actions/clear-action-cache
      - name: Fetch flyte code
        uses: actions/checkout@v4
        with:
          repository: flyteorg/flyte
          path: "${{ github.workspace }}/flyte"
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9
      - shell: bash -el {0}
        working-directory: ${{ github.workspace }}/flyte
        run: |
          conda install -c conda-forge conda-lock
          conda-lock install -n monodocs-env monodocs-environment.lock.yaml
      - shell: bash -el {0}
        working-directory: ${{ github.workspace }}/flyte
        run: |
          conda activate monodocs-env
          export SETUPTOOLS_SCM_PRETEND_VERSION="2.0.0"
          pip install -e ./flyteidl
      - shell: bash -el {0}
        run: |
          conda activate monodocs-env
          pip install -e .
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: Build the documentation
        working-directory: ${{ github.workspace }}/flyte
        shell: bash -el {0}
        env:
          FLYTEKIT_LOCAL_PATH: ${{ github.workspace }}
          DOCSEARCH_API_KEY: fake_docsearch_api_key  # must be set to get doc build to succeed
        run: |
          conda activate monodocs-env
          make -C docs clean html SPHINXOPTS="-W"
